### ISSUE TITLE
Menu click won't navigate back.

### ISSUE THREAD

**Issue by sseyha** [reactazteam/PushyHorizontalMenu#2]
Could you guide me with this?
 I'm beginner, appreciate if you could give me hand.

**Comment by thientran510** [comment]
Could you describe  your problem as much detail as possible or take some screenshots. Then I will give you a hand.

**Comment by sseyha** [comment]
@thientran510 
Sorry for disturb, I know the problem and found the solution now.
I made a mistake... really so sorry.
